extraScrapeConfigs: |-
  - job_name: 'linkerd'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names: ['{{.Namespace}}']

    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_container_name
      action: keep
      regex: ^prometheus$

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="linkerd-proxy"}'
        - '{job="linkerd-controller"}'
