--- 
- name: install nginx and vim
  apt: name=nginx,vim state=present

- name: Copy aviel.txt 
  copy: src=aviel.txt dest=/var1/tmp


- name: Run a command that fails
  ansible.builtin.command: /bin/false